name: check_res
description: A console plugini for user to check the useless resource.
version: 1.0.0
homepage: https://github.com/flutter-all-plugins/check_resource.git

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  process_run: ^0.12.3+2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
